language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - name: "Linux build g++7.3"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - mesa-common-dev
            - libglu1-mesa-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILER_SPEC=linux-g++
        - BOOST_VERSION=1_65_1
      before_install:
        - eval "${MATRIX_EVAL}"
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 20
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20
        - sudo add-apt-repository ppa:beineri/opt-qt596-trusty -y
        - sudo apt-get update -qq
      install:
        # Qt
        - sudo apt-get install -qq qt59base qt59tools qt59webchannel qt59webengine qt59svg
        - source /opt/qt59/bin/qt59-env.sh 

        # Boost
        - wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_${BOOST_VERSION}.tar.gz
        - mkdir boost
        - tar --strip-components=1 -xf boost_${BOOST_VERSION}.tar.gz -C boost
        - rm -f boost_${BOOST_VERSION}.tar.gz
        - cd boost
        - ./bootstrap.sh
        - ./b2 --with-filesystem --with-system link=shared threading=multi toolset=gcc stage
        - export BOOST_INCLUDE="${TRAVIS_BUILD_DIR}/boost"
        - export BOOST_LIB="${TRAVIS_BUILD_DIR}/boost/stage/lib"
        - cd ${TRAVIS_BUILD_DIR}

        # python and its modules
        - sudo python -m pip install tabulate

before_script:
  - mkdir build
  - cd build
  - qmake --version
  - echo BOOST_INCLUDE ${BOOST_INCLUDE}
  - echo BOOST_LIB ${BOOST_LIB}
  - qmake "DISABLE_PYTHON=yes" ../liger.pro -r -spec ${COMPILER_SPEC} 

script:
  - make -s
  - cd tests/bin
  - chmod +x run_all_unit_tests_linux.sh
  - ./run_all_unit_tests_linux.sh
  - python failure_reporter.py .

