language: cpp

sudo: required

matrix:
  include:
#    - name: "MacOS build apple clang 10.0.0"
#      os: osx
#      osx_image: xcode10
#      env:
#        - COMPILER_SPEC=macx-clang
#        - TEST_SCRIPT=run_all_unit_tests.sh
#      install:
#        # Qt5.11.2 
#        - brew install qt5
#        - export PATH="/usr/local/opt/qt/bin:$PATH"
#        
#        # Boost 1.67.0_1
#        - | 
#          if brew ls --versions boost > /dev/null; then
#            brew info boost
#          else
#            brew install boost
#          fi
#        - export BOOST_INCLUDE="/usr/local/Cellar/boost/1.67.0_1/include"
#        - export BOOST_LIB="/usr/local/Cellar/boost/1.67.0_1/lib"
#
#        # python modules
#        - python -m pip install tabulate 

    - name: "Linux build g++7.3"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - mesa-common-dev
            - libglu1-mesa-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILER_SPEC=linux-g++
        - BOOST_SRC=boost_1_65_1.tar.gz
        - BOOST_URL=https://dl.bintray.com/boostorg/release/1.65.1/source
        - BOOST_TOOLSET=gcc
        - TEST_SCRIPT=run_all_unit_tests_linux.sh
      before_install:
        - eval "${MATRIX_EVAL}"
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 20
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20
        - sudo add-apt-repository ppa:beineri/opt-qt596-trusty -y
        - sudo apt-get update -qq
      install:
        # Qt
        - sudo apt-get install -qq qt59base qt59tools qt59webchannel qt59webengine qt59svg
        - source /opt/qt59/bin/qt59-env.sh 

        # Boost
        - wget ${BOOST_URL}/${BOOST_SRC}
        - mkdir boost
        - tar --strip-components=1 -xf ${BOOST_SRC} -C boost
        - rm -f ${BOOST_SRC}
        - cd boost
        - ./bootstrap.sh
        - ./b2 --with-filesystem --with-system link=shared threading=multi toolset=${BOOST_TOOLSET} stage
        - export BOOST_INCLUDE="${TRAVIS_BUILD_DIR}/boost"
        - export BOOST_LIB="${TRAVIS_BUILD_DIR}/boost/stage/lib"
        
        # python modules
        - sudo python -m pip install tabulate 

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - qmake --version
  - python --version
  - echo BOOST_INCLUDE ${BOOST_INCLUDE}
  - echo BOOST_LIB ${BOOST_LIB}
  - qmake "DISABLE_PYTHON=yes" ../liger.pro -r -spec ${COMPILER_SPEC} 

script:
  - make -s
  - cd tests/bin
  - chmod +x ${TEST_SCRIPT}
  - ./${TEST_SCRIPT}
  - python failure_reporter.py .

